# Generated by Django 4.1.2 on 2022-11-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('owner', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
