# Generated by Django 4.1.2 on 2022-11-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentsale',
            old_name='price',
            new_name='price_in_lirs',
        ),
    ]
