# Generated by Django 4.1.2 on 2022-11-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0002_rename_price_rentsale_price_in_lirs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsale',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
