# Generated by Django 4.1.2 on 2022-11-08 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0004_rename_price_in_lirs_rentsale_price_in_lira'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentsale',
            name='created_data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentsale',
            name='updated_time',
            field=models.DateField(auto_now=True),
        ),
    ]
