# Generated by Django 4.1.2 on 2022-11-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0005_rentsale_created_data_rentsale_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsale',
            name='city',
            field=models.CharField(choices=[('ANTAL', 'Antalya')], default='ANTAL', max_length=5),
        ),
        migrations.AlterField(
            model_name='rentsale',
            name='district',
            field=models.CharField(choices=[('ASKE', 'Akseki'), ('AKSU', 'Aksu'), ('ALAN', 'Alanya'), ('DEMR', 'Demre'), ('DESH', 'Döşemealtı'), ('ELMA', 'Elmalı'), ('FINI', 'Finike'), ('GAZI', 'Gazipaşa'), ('GUND', 'Gündoğmuş'), ('IBRA', 'İbradı'), ('KASH', 'Kaş'), ('KEME', 'Kemer'), ('KEPE', 'Kepez'), ('KORK', 'Korkuteli'), ('KUML', 'Kumluca'), ('MANA', 'Manavgat'), ('MURA', 'Muratpaşa'), ('SERI', 'Serik')], default='KEPE', max_length=4),
        ),
        migrations.AlterField(
            model_name='rentsale',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
