# Generated by Django 4.1.2 on 2022-11-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0006_alter_rentsale_city_alter_rentsale_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsale',
            name='district',
            field=models.CharField(choices=[('ASKE', 'Akseki'), ('AKSU', 'Aksu'), ('ALAN', 'Alanya'), ('DEMR', 'Demre'), ('DESH', 'Döşemealtı'), ('ELMA', 'Elmalı'), ('FINI', 'Finike'), ('GAZI', 'Gazipaşa'), ('GUND', 'Gündoğmuş'), ('IBRA', 'İbradı'), ('KASH', 'Kaş'), ('KEME', 'Kemer'), ('KEPE', 'Kepez'), ('KORK', 'Korkuteli'), ('KONY', 'Konyaaltı'), ('KUML', 'Kumluca'), ('MANA', 'Manavgat'), ('MURA', 'Muratpaşa'), ('SERI', 'Serik')], default='KEPE', max_length=4),
        ),
    ]
