# Generated by Django 4.1.2 on 2022-11-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0007_alter_rentsale_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentsale',
            name='type',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], default='R', max_length=1),
        ),
    ]
