# Generated by Django 4.1.2 on 2022-11-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0008_rentsale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentsale',
            name='description',
            field=models.TextField(default=' ', max_length=2000),
        ),
    ]
