# Generated by Django 4.1.2 on 2022-11-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0009_rentsale_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsale',
            name='description',
            field=models.TextField(default=None, max_length=2000),
        ),
    ]
