# Generated by Django 4.1.2 on 2022-11-28 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0016_image_alter_rentsale_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsale',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_menu.image'),
        ),
    ]
