# Generated by Django 4.1.2 on 2022-12-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0020_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('rentsale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_menu.rentsale')),
            ],
        ),
    ]
