# Generated by Django 4.1.2 on 2022-12-04 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_menu', '0021_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentsale',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='rentsale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='main_menu.rentsale'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
