# Generated by Django 4.1.2 on 2022-12-04 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0022_rentsale_user_alter_picture_rentsale_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentsale',
            name='user',
        ),
    ]
