# Generated by Django 4.1.2 on 2022-12-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0026_alter_clientrequest_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientRequest',
        ),
    ]
