# Generated by Django 4.1.2 on 2022-12-14 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0028_clientrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
