# Generated by Django 4.1.2 on 2022-12-18 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0029_alter_clientrequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='name',
            field=models.CharField(help_text='Input your name ', max_length=40, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
