# Generated by Django 4.1.2 on 2022-12-18 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0030_alter_clientrequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='email',
            field=models.EmailField(blank=True, help_text='Your email (optional)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Your message', null=True),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='name',
            field=models.CharField(help_text='Input your name', max_length=40, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='phone',
            field=models.IntegerField(help_text='Phone number'),
        ),
    ]
