# Generated by Django 4.1.2 on 2022-12-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0033_remove_rentsale_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentsale',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
