# Generated by Django 4.1.2 on 2022-12-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0034_rentsale_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentsale',
            name='slug',
        ),
    ]
