# Generated by Django 4.1.2 on 2022-12-19 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0035_remove_rentsale_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='email_ar',
            field=models.EmailField(blank=True, help_text='Your email (optional)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='email_en',
            field=models.EmailField(blank=True, help_text='Your email (optional)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='email_ru',
            field=models.EmailField(blank=True, help_text='Your email (optional)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='email_tr',
            field=models.EmailField(blank=True, help_text='Your email (optional)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='message_ar',
            field=models.TextField(blank=True, help_text='Your message', null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='message_en',
            field=models.TextField(blank=True, help_text='Your message', null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='message_ru',
            field=models.TextField(blank=True, help_text='Your message', null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='message_tr',
            field=models.TextField(blank=True, help_text='Your message', null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='name_ar',
            field=models.CharField(help_text='Input your name', max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='name_en',
            field=models.CharField(help_text='Input your name', max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='name_ru',
            field=models.CharField(help_text='Input your name', max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='name_tr',
            field=models.CharField(help_text='Input your name', max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='phone_ar',
            field=models.IntegerField(help_text='Phone number', null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='phone_en',
            field=models.IntegerField(help_text='Phone number', null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='phone_ru',
            field=models.IntegerField(help_text='Phone number', null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='phone_tr',
            field=models.IntegerField(help_text='Phone number', null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='address_ar',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='address_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='address_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='address_tr',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='city_ar',
            field=models.CharField(choices=[('ANTAL', 'Antalya')], default='ANTAL', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='city_en',
            field=models.CharField(choices=[('ANTAL', 'Antalya')], default='ANTAL', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='city_ru',
            field=models.CharField(choices=[('ANTAL', 'Antalya')], default='ANTAL', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='city_tr',
            field=models.CharField(choices=[('ANTAL', 'Antalya')], default='ANTAL', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='created_data_ar',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='created_data_en',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='created_data_ru',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='created_data_tr',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='district_ar',
            field=models.CharField(choices=[('ASKE', 'Akseki'), ('AKSU', 'Aksu'), ('ALAN', 'Alanya'), ('DEMR', 'Demre'), ('DESH', 'Döşemealtı'), ('ELMA', 'Elmalı'), ('FINI', 'Finike'), ('GAZI', 'Gazipaşa'), ('GUND', 'Gündoğmuş'), ('IBRA', 'İbradı'), ('KASH', 'Kaş'), ('KEME', 'Kemer'), ('KEPE', 'Kepez'), ('KORK', 'Korkuteli'), ('KONY', 'Konyaaltı'), ('KUML', 'Kumluca'), ('MANA', 'Manavgat'), ('MURA', 'Muratpaşa'), ('SERI', 'Serik')], default='KEPE', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='district_en',
            field=models.CharField(choices=[('ASKE', 'Akseki'), ('AKSU', 'Aksu'), ('ALAN', 'Alanya'), ('DEMR', 'Demre'), ('DESH', 'Döşemealtı'), ('ELMA', 'Elmalı'), ('FINI', 'Finike'), ('GAZI', 'Gazipaşa'), ('GUND', 'Gündoğmuş'), ('IBRA', 'İbradı'), ('KASH', 'Kaş'), ('KEME', 'Kemer'), ('KEPE', 'Kepez'), ('KORK', 'Korkuteli'), ('KONY', 'Konyaaltı'), ('KUML', 'Kumluca'), ('MANA', 'Manavgat'), ('MURA', 'Muratpaşa'), ('SERI', 'Serik')], default='KEPE', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='district_ru',
            field=models.CharField(choices=[('ASKE', 'Akseki'), ('AKSU', 'Aksu'), ('ALAN', 'Alanya'), ('DEMR', 'Demre'), ('DESH', 'Döşemealtı'), ('ELMA', 'Elmalı'), ('FINI', 'Finike'), ('GAZI', 'Gazipaşa'), ('GUND', 'Gündoğmuş'), ('IBRA', 'İbradı'), ('KASH', 'Kaş'), ('KEME', 'Kemer'), ('KEPE', 'Kepez'), ('KORK', 'Korkuteli'), ('KONY', 'Konyaaltı'), ('KUML', 'Kumluca'), ('MANA', 'Manavgat'), ('MURA', 'Muratpaşa'), ('SERI', 'Serik')], default='KEPE', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='district_tr',
            field=models.CharField(choices=[('ASKE', 'Akseki'), ('AKSU', 'Aksu'), ('ALAN', 'Alanya'), ('DEMR', 'Demre'), ('DESH', 'Döşemealtı'), ('ELMA', 'Elmalı'), ('FINI', 'Finike'), ('GAZI', 'Gazipaşa'), ('GUND', 'Gündoğmuş'), ('IBRA', 'İbradı'), ('KASH', 'Kaş'), ('KEME', 'Kemer'), ('KEPE', 'Kepez'), ('KORK', 'Korkuteli'), ('KONY', 'Konyaaltı'), ('KUML', 'Kumluca'), ('MANA', 'Manavgat'), ('MURA', 'Muratpaşa'), ('SERI', 'Serik')], default='KEPE', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='floor_ar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='floor_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='floor_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='floor_tr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='owner_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='owner_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='owner_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='owner_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='phone_number_ar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='phone_number_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='phone_number_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='phone_number_tr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='price_in_lira_ar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='price_in_lira_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='price_in_lira_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='price_in_lira_tr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='room_ar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='room_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='room_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='room_tr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='square_ar',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='square_en',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='square_ru',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='square_tr',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='type_ar',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], default='R', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='type_en',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], default='R', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='type_ru',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], default='R', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='type_tr',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], default='R', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='updated_time_ar',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='updated_time_en',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='updated_time_ru',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='updated_time_tr',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
