# Generated by Django 4.1.2 on 2022-12-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0037_remove_rentsale_address_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentsale',
            name='address_ar',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='address_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='address_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='address_tr',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='city_ar',
            field=models.CharField(choices=[('ANTAL', 'Antalya')], default='ANTAL', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='city_en',
            field=models.CharField(choices=[('ANTAL', 'Antalya')], default='ANTAL', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='city_ru',
            field=models.CharField(choices=[('ANTAL', 'Antalya')], default='ANTAL', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='city_tr',
            field=models.CharField(choices=[('ANTAL', 'Antalya')], default='ANTAL', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='created_data_ar',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='created_data_en',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='created_data_ru',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='created_data_tr',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='district_ar',
            field=models.CharField(choices=[('ASKE', 'Akseki'), ('AKSU', 'Aksu'), ('ALAN', 'Alanya'), ('DEMR', 'Demre'), ('DESH', 'Döşemealtı'), ('ELMA', 'Elmalı'), ('FINI', 'Finike'), ('GAZI', 'Gazipaşa'), ('GUND', 'Gündoğmuş'), ('IBRA', 'İbradı'), ('KASH', 'Kaş'), ('KEME', 'Kemer'), ('KEPE', 'Kepez'), ('KORK', 'Korkuteli'), ('KONY', 'Konyaaltı'), ('KUML', 'Kumluca'), ('MANA', 'Manavgat'), ('MURA', 'Muratpaşa'), ('SERI', 'Serik')], default='KEPE', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='district_en',
            field=models.CharField(choices=[('ASKE', 'Akseki'), ('AKSU', 'Aksu'), ('ALAN', 'Alanya'), ('DEMR', 'Demre'), ('DESH', 'Döşemealtı'), ('ELMA', 'Elmalı'), ('FINI', 'Finike'), ('GAZI', 'Gazipaşa'), ('GUND', 'Gündoğmuş'), ('IBRA', 'İbradı'), ('KASH', 'Kaş'), ('KEME', 'Kemer'), ('KEPE', 'Kepez'), ('KORK', 'Korkuteli'), ('KONY', 'Konyaaltı'), ('KUML', 'Kumluca'), ('MANA', 'Manavgat'), ('MURA', 'Muratpaşa'), ('SERI', 'Serik')], default='KEPE', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='district_ru',
            field=models.CharField(choices=[('ASKE', 'Akseki'), ('AKSU', 'Aksu'), ('ALAN', 'Alanya'), ('DEMR', 'Demre'), ('DESH', 'Döşemealtı'), ('ELMA', 'Elmalı'), ('FINI', 'Finike'), ('GAZI', 'Gazipaşa'), ('GUND', 'Gündoğmuş'), ('IBRA', 'İbradı'), ('KASH', 'Kaş'), ('KEME', 'Kemer'), ('KEPE', 'Kepez'), ('KORK', 'Korkuteli'), ('KONY', 'Konyaaltı'), ('KUML', 'Kumluca'), ('MANA', 'Manavgat'), ('MURA', 'Muratpaşa'), ('SERI', 'Serik')], default='KEPE', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='district_tr',
            field=models.CharField(choices=[('ASKE', 'Akseki'), ('AKSU', 'Aksu'), ('ALAN', 'Alanya'), ('DEMR', 'Demre'), ('DESH', 'Döşemealtı'), ('ELMA', 'Elmalı'), ('FINI', 'Finike'), ('GAZI', 'Gazipaşa'), ('GUND', 'Gündoğmuş'), ('IBRA', 'İbradı'), ('KASH', 'Kaş'), ('KEME', 'Kemer'), ('KEPE', 'Kepez'), ('KORK', 'Korkuteli'), ('KONY', 'Konyaaltı'), ('KUML', 'Kumluca'), ('MANA', 'Manavgat'), ('MURA', 'Muratpaşa'), ('SERI', 'Serik')], default='KEPE', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='floor_ar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='floor_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='floor_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='floor_tr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='room_ar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='room_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='room_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='room_tr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='square_ar',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='square_en',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='square_ru',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='square_tr',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='type_ar',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], default='R', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='type_en',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], default='R', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='type_ru',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], default='R', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='rentsale',
            name='type_tr',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], default='R', max_length=1, null=True),
        ),
    ]
