# Generated by Django 4.1.2 on 2022-12-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0039_remove_rentsale_address_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequest',
            name='email_ar',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='email_tr',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='message_ar',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='message_tr',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='name_tr',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='phone_ar',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='phone_en',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='phone_ru',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='phone_tr',
        ),
    ]
